### ISSUE TITLE
Wrong tag and output format

### ISSUE THREAD

**Issue by andrewkatz** [WyriHaximus/github-action-get-previous-tag#38]
I've been using this and the next-semvers for a long time without issue, but after the latest update an hour ago, I'm seeing the following issues:

Finding the wrong tag. It's outputting my oldest tag `v1.0.0` when it should be something way higher in the 600's.

Then it looks like the new way of outputting the tags that was merged in https://github.com/WyriHaximus/github-action-get-previous-tag/pull/36 is breaking next-semvers, possibly from the extra newlines.

```
Fatal error: Uncaught Version\Exception\InvalidVersionString: Version string 'v1.0.0
' is not valid and cannot be parsed in /workdir/vendor/nikolaposa/version/src/Exception/InvalidVersionString.php:16
Stack trace:
#0 /workdir/vendor/nikolaposa/version/src/Version.php(65): Version\Exception\InvalidVersionString::notParsable('v1.0.0\r')
#1 /workdir/src/Next.php(25): Version\Version::fromString('v1.0.0\r')
#2 /workdir/next.php(14): WyriHaximus\Github\Actions\NextSemVers\Next::run('v1.0.0\r', true)
#3 /workdir/next.php(17): {closure}()
#4 {main}
  thrown in /workdir/vendor/nikolaposa/version/src/Exception/InvalidVersionString.php on line 16
```

Let me know if there's anything else I can help with in troubleshooting.

**Comment by andrewkatz** [comment]
For comparison, here's the old and new ways ran in my project:

Old way:
```
$ git for-each-ref --sort=-taggerdate --count 1 --format="%(refname:short)" "refs/tags/*"
v1.0.0
```

New way:
```
$ git rev-list --tags --max-count=1                                                      
d1417029a6569bef6b5158e91712063c1c58ab32

$ git describe --tags d1417029a6569bef6b5158e91712063c1c58ab32                           
v636.0.0
```

**Comment by andrewkatz** [comment]
More info to show that the timestamps of my tags aren't messed up. Clear that `v1.0.0` is not the latest tag.

```
$ git log -1 --format=%at v636.0.0                            
1666633966

$ main git log -1 --format=%at v1.0.0  
1616603188
```

**Comment by andrewkatz** [comment]
Looks like the sorting by `taggerdate` isn't actually sorting the tags.

```
$ git for-each-ref --sort=-taggerdate --format="%(refname:short)" "refs/tags/*" 
v1.0.0
v10.0.0
v100.0.0
v101.0.0
v102.0.0
v103.0.0
v104.0.0
v105.0.0
v106.0.0
v107.0.0
v108.0.0
v109.0.0
# ...

$ git for-each-ref --format="%(refname:short)" "refs/tags/*" 
v1.0.0
v10.0.0
v100.0.0
v101.0.0
v102.0.0
v103.0.0
v104.0.0
v105.0.0
v106.0.0
v107.0.0
v108.0.0
v109.0.0
# ...
```

**Comment by andrewkatz** [comment]
Looks like sorting by `-creatordate` fixes the issue.

```
$ git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/*"
v636.0.0
```

**Comment by andrewkatz** [comment]
Proposed a fix https://github.com/WyriHaximus/github-action-get-previous-tag/pull/39

**Comment by andrewkatz** [comment]
Proposed fix for output issue https://github.com/WyriHaximus/github-action-get-previous-tag/pull/40

**Comment by WyriHaximus** [comment]
@andrewkatz Just released a new version to deal with GitHub changes and also merged in a fix. Thanks for the quick catch and fix. Will release it shortly. However, it looks like that '\r` is something that also requires fixing.

**Comment by andrewkatz** [comment]
Going to close this issue and move any discussion to the PR. Thanks for acting quickly @WyriHaximus

**Comment by WyriHaximus** [comment]
Cheers, will tag a new release when #40 is in and let you know here.

**Comment by WyriHaximus** [comment]
@andrewkatz Just tagged [`v1.2.1`](https://github.com/WyriHaximus/github-action-get-previous-tag/releases/tag/v1.2.1). Please let me know if you run into any further trouble, or when it fixed it as we intended.

**Comment by andrewkatz** [comment]
Just re-ran my workflow and all is good now, thanks!

**Comment by WyriHaximus** [comment]
Great, thanks for creating a fix and confirming it works after releasing it :+1: .
