### ISSUE TITLE
Option to define git directory

### ISSUE THREAD

**Issue by piranna** [WyriHaximus/github-action-get-previous-tag#48]
Add an option to define the path where the git directory exists, instead of using just current repo folder root.

**Comment by WyriHaximus** [comment]
Sounds like a good idea. Been working on moving most of my workflows into a central repository, and also need working directory there.

**Comment by gfolcarelli** [comment]
hi! Do you have any update about this feature?

**Comment by WyriHaximus** [comment]
Started implementing this in #51

**Comment by WyriHaximus** [comment]
This has just been released through: https://github.com/WyriHaximus/github-action-get-previous-tag/releases/tag/v1.4.0
