### ISSUE TITLE
Replace Node.js 16 with Node.js 20

### ISSUE THREAD

**Issue by Gershon-A** [WyriHaximus/github-action-get-previous-tag#50]
GitHub actions is planning to [deprecate Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The file existence action is still using Node 16. We are getting this warning that the file exists action should be updated to Node 20

**Comment by WyriHaximus** [comment]
Feel free to create a PR addressing this, should be a quick an easy edit through the GitHub.com UI: https://github.com/WyriHaximus/github-action-composer-php-versions-in-range/pull/29

**Comment by WyriHaximus** [comment]
This has been resolved through #50, will release 1.4 with this once the PR for #48 is in. Probably today.
